language: c

sudo: required

notifications:
  email: false

before_install:
  # build cmocka
  - mkdir cmocka_build
  - wget https://cmocka.org/files/1.1/cmocka-1.1.1.tar.xz
  - xz -d cmocka-1.1.1.tar.xz
  - tar -x < cmocka-1.1.1.tar
  - rm cmocka-1.1.1.tar
  - cd cmocka_build
  - cmake ../cmocka-1.1.1
  - make
  - cd ..
  # build valgrind
  - wget ftp://sourceware.org/pub/valgrind/valgrind-3.13.0.tar.bz2
  - bzip2 -d valgrind-3.13.0.tar.bz2
  - tar -x < valgrind-3.13.0.tar
  - rm valgrind-3.13.0.tar
  - cd valgrind-3.13.0
  - ./configure
  - make
  - cd ..

install: 
  # install cmocka
  - cd cmocka_build
  - sudo make install
  - sudo ldconfig
  - cd ..
  # install valgrind
  - cd valgrind-3.13.0
  - sudo make install
  - cd ..
  # install libc debugging symbols for valgrind
  - sudo apt-get -y install libc6-dbg

before_script:
  # make voyager
  - make

script:
  # run tests
  - ./tests
  - valgrind --leak-check=full --error-exitcode=1 ./tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
